### PR TITLE
Correct line wrapping for documentation generated by breathe.

### LINKED ISSUE #16: Improve autodoc style for 'breathe' entities
Hi there!

I am loving the python formatting for autodoc entries, so I would like to switch to this Sphinx theme. However, to keep things consistent, we also need to migrate the documentation of our C and C++ api's. They are generated with the 'breathe' python package. Sadly, they don't look so nice yet. I have looked at the js snippet that inserts the styles and <br>s in the right spots and I think it should be fairly straightforward to add a case for 'breathe' autodocs but I am not quite in the know on how this theme works, so before I dive in to try to do it myself I thought it post first.

Here is the html of a breathe generated function:
```html
<dl class="cpp function">
   <dt class="sig sig-object cpp" id="_CPPv421dds_assert_liveliness12dds_entity_t">
      <span id="_CPPv321dds_assert_liveliness12dds_entity_t"></span>
      <span id="_CPPv221dds_assert_liveliness12dds_entity_t"></span>
      <span id="dds_assert_liveliness__dds_entity_t"></span>
      <span class="target" id="dds_8h_1a4face9db6e18ba6808bdbf7f4220209e"></span>
      <span class="n">
         <span class="pre">dds_return_t</span>
      </span>
      <span class="w"> </span>
      <span class="sig-name descname">
         <span class="n">
            <span class="pre">dds_assert_liveliness</span>
         </span>
      </span>
      <span class="sig-paren">(</span>
      <a class="reference internal" href="typedef_dds__basic__types_8h_1aa66538468c533a9ea558b7e280677b13.html#_CPPv412dds_entity_t" title="dds_entity_t">
       <span class="n">
         <span class="pre">dds_entity_t</span>
       </span>
      </a>
      <span class="w"> </span>
      <span class="n sig-param"> 
        <span class="pre">entity</span>
      </span>
      <span class="sig-paren">)</span>
      <a class="headerlink" href="#_CPPv421dds_assert_liveliness12dds_entity_t" title="Permalink to this definition">¶</a>
      <br />
   </dt>
   <dd>
      <p>This operation manually asserts the liveliness of a writer or domain participant. </p>
      <p>This operation manually asserts the liveliness of a writer or domain participant. This is used in combination with the Liveliness QoS policy to indicate that the entity remains active. This operation need only be used if the liveliness kind in the QoS is either DDS_LIVELINESS_MANUAL_BY_PARTICIPANT or DDS_LIVELINESS_MANUAL_BY_TOPIC.</p>
      <dl class="field-list simple">
         <dt class="field-odd">Parameters</dt>
         <dd class="field-odd">
            <p><strong>entity</strong> – <strong>[in]</strong> A domain participant or writer</p>
         </dd>
         <dt class="field-even">Return values</dt>
         <dd class="field-even">
            <ul class="simple">
               <li>
                  <p><strong>DDS_RETCODE_OK</strong> – The operation was successful. </p>
               </li>
               <li>
                  <p><strong>DDS_RETCODE_ILLEGAL_OPERATION</strong> – The operation is invoked on an inappropriate object. </p>
               </li>
            </ul>
         </dd>
         <dt class="field-odd">Returns</dt>
         <dd class="field-odd">
            <p>A dds_return_t indicating success or failure.</p>
         </dd>
      </dl>
   </dd>
</dl>
```

Let me know if you're interested in adding support for my usecase. Cheers!

### PR DESCRIPTION
**Pull request by thijsmie**
I've spent some time to do a similar line wrapping implementation for breathe entities. It needed a little more coaxing then the python one but I think I've managed to cover all cases now. Let me know if anything needs changing.

Fixes #16

docu

### CODE REVIEW

**Comment by dantownsend** [comment]
@thijsmie This looks great, thanks 👍 

Is there any way we could show autodoc working with a C++ file on the [demo page](https://piccolo-theme.readthedocs.io/en/latest/demo.html)? That way it will be easier to detect if something breaks in the future. I'm not too familiar with breathe, so not sure how to go about it.

**Comment by thijsmie** [comment]
Sure could! Are you okay with introducing breathe as a dependency in doc-requirements? I checked, it itself only depends on docutils and Sphinx so it doesn't introduce new dependencies beyond that.

**Comment by dantownsend** [comment]
@thijsmie That's fine with me

**Comment by dantownsend** [comment]
Looks great, thanks! Will get it released.

**Pull request merged**
