### PR TITLE
Add support for C

### PR DESCRIPTION
**Pull request by thijsmie**
Turns out my C++ support also works when `breathe` is forced into C mode, it is just the classname that is changing (and functions in the search index actually show up as C function instead of C++). Some minor changes are required to make it work with the theme again.

### CODE REVIEW

**Comment by thijsmie** [comment]
Oh, I've detected one issue still...

**Comment by thijsmie** [comment]
The :not() selectors get in the way, but the section titles get a little background header. Those are now not the prettiest in dark mode but it works.

**Comment by dantownsend** [comment]
@thijsmie Thanks a lot for this. If not too much trouble, can you add a C snippet to the demo page?

**Comment by dantownsend** [comment]
Looks great, thanks 👍

**Comment by dantownsend** [comment]
It's on PyPI now - version 0.9.0

**Pull request merged**
